[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
ffi = false
fs_permissions = []
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "v4-core/=lib/v4-core/src/",
    "solmate/=lib/solmate/",
]

[fuzz]
runs = 256

[invariant]
runs = 32
depth = 64
fail_on_revert = false

[fmt]
line_length = 120

[lint]
lint_on_build = false
